package com.seat.reserve.api;

public enum ErrorCode {
	UNAUTHORIZED,
	FORBIDDEN,
	NOT_FOUND,
	SEAT_TAKEN,
	PER_USER_LIMIT,
	IDEMPOTENCY_DIFFERENT_BODY,
	IDEMPOTENCY_IN_PROGRESS,
	BAD_REQUEST,
	INVALID_STATE
}
